name: publish_kv_sessions

on:
  push:
    paths: 
      - 'kv_sessions/gleam.toml'

jobs:
  check_version:
      runs-on: ubuntu-latest
      outputs:
        version_changed: ${{ steps.check_version.outputs.version_changed }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Check if version changed
          id: check_version
          run: |
            # Extract current version
            current_version=$(grep '^version = ' kv_sessions/gleam.toml | cut -d '"' -f2)
            # Extract previous version from git history
            previous_version=$(git show HEAD~1:kv_sessions/gleam.toml | grep '^version = ' | cut -d '"' -f2 || echo "not_found")

            # Compare versions
            if [ "$current_version" != "$previous_version" ]; then
              echo "Version changed from $previous_version to $current_version"
              echo "version_changed=true" >> $GITHUB_ENV
            else
              echo "version_changed=false" >> $GITHUB_ENV
            fi
          env:
            GITHUB_ENV: ${{ steps.check_version.outputs.version_changed }}

  test:
    runs-on: ubuntu-latest
    needs: check_version
    if: needs.check_version.outputs.version_changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - name: "Download dependencies"
        run: gleam deps download
      - name: "Run tests"
        working-directory: ./kv_sessions
        run: gleam test
      - name: "Lint formatting"
        working-directory: ./kv_sessions
        run: gleam format --check src test

  deploy: 
    needs: 
      - check_version
      - test
    if: needs.check_version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: "${{secrets.OP_SERVICE_ACCOUNT_TOKEN}}"
          HEXPM_USER: "op://hex/Hex/username"
          HEXPM_PASS: "op://hex/Hex/password"

      - name: Publish kv_sessions
        run: gleam publish --yes
        working-directory: ./kv_sessions
