name: publish_kv_sessions_postgres_adapter

on:
  push:
    paths: 
      - 'kv_sessions_postgres_adapter/gleam.toml'

jobs:
  check_version:
      runs-on: ubuntu-latest
      outputs:
        is_changed: ${{ steps.output_step.outputs.is_changed }}
      steps:
        - name: Install just 
          uses: extractions/setup-just@v2
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 2 # Fetch enough history to compare HEAD~1
        - name: Check Version
          id: output_step
          run: |
            IS_CHANGED=$(just ci_check_version kv_sessions_postgres_adapter)
            echo "Is changed: $IS_CHANGED"
            echo "is_changed=$IS_CHANGED" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs: check_version
    if: (needs.check_version.outputs.is_changed == 'true')
    services:
      postgres:
        image: postgres # Docker Hub image
        env:
          POSTGRES_PASSWORD: mySuperSecretPassword!
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Install just 
        uses: extractions/setup-just@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.2.0"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      - name: "Download dependencies"
        run: just ci_deps kv_sessions_postgres_adapter
      - name: "Run tests"
        run: cd kv_sessions_postgres_adapter && gleam test
      - name: "Lint formatting"
        run: just ci_format kv_sessions_postgres_adapter

  deploy: 
    needs: 
      - check_version
      - test
    if: (needs.check_version.outputs.is_changed == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Install just 
        uses: extractions/setup-just@v2
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.2.0"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: "${{secrets.OP_SERVICE_ACCOUNT_TOKEN}}"
          HEXPM_USER: "op://hex/Hex/username"
          HEXPM_PASS: "op://hex/Hex/password"

      - name: Publish kv_sessions_postgres_adapter
        run: just ci_publish kv_sessions_postgres_adapter

