name: publish_kv_sessions

on:
  push:
    # paths: 
    #   - 'kv_sessions/gleam.toml'

jobs:
  check_version:
      runs-on: ubuntu-latest
      outputs:
        is_changed: ${{ steps.check_version.outputs.is_changed }}
      steps:
        - name: Install just 
          uses: extractions/setup-just@v2
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Check Version
          run: |
            IS_CHANGED=$(just ci_check_version kv_sessions)
            echo "Is changed: $IS_CHANGED"
            echo "::set-output name=is_changed::$IS_CHANGED"

  test:
    runs-on: ubuntu-latest
    needs: check_version
    if: needs.check_version.outputs.is_changed == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      - name: "Download dependencies"
        run: just ci_deps kv_sessions
      - name: "Run tests"
        run: just ci_test kv_sessions
      - name: "Lint formatting"
        run: just ci_format kv_sessions

  deploy: 
    needs: 
      - check_version
      - test
    if: needs.check_version.outputs.is_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Install just 
        uses: extractions/setup-just@v2
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.4.1"
          rebar3-version: "3"
      
      - name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: "${{secrets.OP_SERVICE_ACCOUNT_TOKEN}}"
          HEXPM_USER: "op://hex/Hex/username"
          HEXPM_PASS: "op://hex/Hex/password"

      - name: Publish kv_sessions
        run: just ci_publish kv_sessions
